### ISSUE TITLE
grpc not mentioned in this repo; shouldn't it be?

### ISSUE THREAD

**Issue by timotheecour** [oswjk/nimtwirp#1]
* seems like this allows implementing grpc servers in nim; why not mention grpc in readme and package keyword/description?
Or maybe I'm misunderstanding it

* grpc supports Bi-directional streaming (both for input and output); is that the case for nimtwirp? wasn't clear from readme

## links
* see also: [Could this be used for gRPC? · Issue #9 · oswjk/nimpb](https://github.com/oswjk/nimpb/issues/9)

**Comment by oskaritimperi** [comment]
I don't think you can directly use Twirp as a drop-in replacement for gRPC, because the two protocols have a bit different error codes. If the error codes were compatible, then I think you could use Twirp as a simple replacement. There's another RPC protocol, which is more compatible: http://nodir.io/post/138899670556/prpc but I haven't looked much into that.

You  can read more about Twirp and it's background from the announcement blog post: https://blog.twitch.tv/twirp-a-sweet-new-rpc-framework-for-go-5f2febbf35f

Twirp does not support streaming. I'm not sure how you could implement that on top of HTTP 1.x, which Twirp is based on. As I understand it, gRPC uses HTTP2 to support the advanced use cases, like streaming.
